version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailpit
