version: '3.8'

services:
  app:
    build:
      context: .
    container_name: email_service
    command: ./mvnw spring-boot:run
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailpit
