version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_email
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_notifications
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  pg_data:
