spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted  
  info:
    env:
      enabled: true
  server:
    port: 8080

info:
  app:
    name: email-api-mailpit
    description: API for managing users and sending emails
    version: 1.0
    developer:
      name: Your Name
      email: youremail@example.com

logging:
  level:
    root: INFO
